### ISSUE TITLE
raid volumes do not remove existing data from member disks as needed before creation

### ISSUE THREAD

**Issue by dwlehman** [linux-system-roles/storage#163]
It should use `self._blivet.devicetree.recursive_remove` like `BlivetPool._create_members` does.

**Comment by AbdelAzizMohamedMousa** [comment]
It is generally recommended to remove existing data from member disks before creating a RAID volume to avoid potential data loss or corruption. The recommended way to do this in Blivet is to use the recursive_remove() method of the DeviceTree object.

In the code snippet you provided, it seems that the recursive_remove() method is not used to remove existing data from member disks before creating a RAID volume. To ensure that existing data is removed, you can modify the code to use recursive_remove() as follows: 
`def create(self):
    for device in self.devices:
        # remove existing data from member disks
        self._blivet.devicetree.recursive_remove(device)
        
    # create RAID volume
    self._blivet.devicetree.add_device(self._blivet.dmraid_factory(*self.devices))
`
By calling recursive_remove() on each device before creating the RAID volume, you can ensure that any existing data on the member disks is removed.

**Comment by japokorn** [comment]
Fixed by #169.
