### ISSUE TITLE
query for VDO

### ISSUE THREAD

**Issue by taru-svg** [linux-system-roles/storage#167]
Any idea, when is VDO (Virtual Disk Optimiser) planned to provided in rhel 7.
#rhel7 #vdo @richm @seocam @tyll @tabowling @nhosoi

**Comment by richm** [comment]
> Any idea, when is VDO (Virtual Disk Optimiser) planned to provided in rhel 7. #rhel7 #vdo @richm @seocam @tyll @tabowling @nhosoi

I don't know, but the role currently supports VDO

**Comment by tabowling** [comment]
I know RHEL 8 and 9 have it.  I thought it landed in RHEL 7 already.  If not, it is outside the maintenance phase for 7 so would never get it directly, unless by a third party repo.  I'll ask some experts on the matter to chime in.

**Comment by dwlehman** [comment]
My understanding is that the role's support for VDO uses lvm-vdo, which is not in RHEL 7.

@vojtechtrefny is this accurate?

**Comment by nhosoi** [comment]
> My understanding is that the role's support for VDO uses lvm-vdo, which is not in RHEL 7.
> 
> @vojtechtrefny is this accurate?

The current system-roles in rhel-7.9 is in sync with rhel-8.5. I.e., the storage role in rhel-7.9 contains the VDO support, which should not be? Do we need to eliminate or disable something in the system-roles for rhel-7? (Or is it a doc issue?)

**Comment by richm** [comment]
> > My understanding is that the role's support for VDO uses lvm-vdo, which is not in RHEL 7.
> > @vojtechtrefny is this accurate?
> 
> The current system-roles in rhel-7.9 is in sync with rhel-8.5. I.e., the storage role in rhel-7.9 contains the VDO support, which should not be? Do we need to eliminate or disable something in the system-roles for rhel-7? (Or is it a doc issue?)

I think this is a doc issue, at least for now.

**Comment by vojtechtrefny** [comment]
> My understanding is that the role's support for VDO uses lvm-vdo, which is not in RHEL 7.
> 
> @vojtechtrefny is this accurate?

Yes, that's correct. We don't support the standalone VDO devices that are available in RHEL 7, only LVM VDO devices available in RHEL 8 and 9. We don't even have support in blivet for this and there are currently no plans to add the support.

> I think this is a doc issue, at least for now.

The README mentions that `deduplication` and `compression` is valid only for LVM volumes. Maybe we could make that clearer?
