### ISSUE TITLE
flake8 and yamllint errors

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/storage#173]
This is an output from tox/travis tests. Flake8 and yamllint failed with some errors.
http://pastebin.test.redhat.com/906397
Could you please fix them?

**Comment by richm** [comment]
The storage role disables flake8 and black: https://github.com/linux-system-roles/storage/blob/master/.travis/config.sh#L59-L62
and disables yamllint line length checking: https://github.com/linux-system-roles/storage/blob/master/.yamllint.yml#L17
