### ISSUE TITLE
Creating EXT4 disk via storage_volumes hangs when mke2fs requests input

### ISSUE THREAD

**Issue by CDann3r** [linux-system-roles/storage#180]
Using this role to configure "storage_volumes" on RHEL 7.6 to create EXT4 FS.

The blivet_output of the role before creating the FS.
`"volumes": [
            {
                "_device": "/dev/sdh",
                "_mount_id": "UUID=f982878c-14b0-487d-91ce-ff75984cce45",
                "disks": [
                    "sdh"
                ],
                "fs_create_options": "",
                "fs_label": "hdfs_data4",
                "fs_overwrite_existing": true,
                "fs_type": "ext4",
                "mount_check": 0,
                "mount_device_identifier": "uuid",
                "mount_options": "defaults,noatime,discard,barrier=0",
                "mount_passno": 0,
                "mount_point": "/data4",
                "name": "hdfs_data4",
                "size": "1024g",
                "state": "present",
                "type": "disk"
            }`

The role hangs wile creating the EXT4 FS directly on disk.
On htop I can see the following command:
`mke2fs -t ext4 /dev/sdh`
![image](https://user-images.githubusercontent.com/14169112/101336568-ed19f900-387a-11eb-91d8-8af4079628af.png)

When executing this command directly on the node it requests user input to proceed.
![image](https://user-images.githubusercontent.com/14169112/101336984-6a456e00-387b-11eb-8e19-cab42b1473b1.png)

I fixed this by aborting the current running "system-linux-roles.storage" and executed ansible ad-hoc commands to create them by: 
`ansible <hostgroup> --private-key <path-to-private-key> -m shell -b -a "echo y | mke2fs -t ext4 /dev/sdh"`

Expected Behaviour:
The role shouldn't halt when creating EXT4 filesystems directly on disk and should auto approve mke2fs request.

**Comment by pcahyna** [comment]
Thanks for the report. This sounds very much like #122 that I fixed in #154. What version of the role are you using and where did you get it from?

**Comment by CDann3r** [comment]
I installed the role via galaxy command just this week.
This got the me the version: 
`ansible-galaxy role install linux-system-roles.storage --force`

`Role: linux-system-roles.storage/
        description: Configure volumes and filesystems
        active: True
        commit: e990c1ff13151314f5cebda7f8baa5d3e3748573
        commit_message: Merge pull request #177 from richm/issue-67

issue-67: Create storage_lsr sub-directory under module_utils and move size.py there
        commit_url: https://api.github.com/repos/linux-system-roles/storage/git/commits/e990c1ff13151314f5cebda7f8baa5d3e374857
        company: Red Hat, Inc.
        created: 2018-12-14T17:40:24.285509Z
        download_count: 7557
        forks_count: 22
        galaxy_info:
                author: David Lehman <dlehman@redhat.com>
                company: Red Hat, Inc.
                galaxy_tags: ['system', 'lvm', 'storage', 'redhat', 'rhel', 'fedora', 'centos']
                license: MIT
                min_ansible_version: 2.5
                platforms: [{'name': 'Fedora', 'versions': [31, 32]}, {'name': 'EL', 'versions': [7, 8]}]
        github_branch: master
        github_repo: storage
        github_user: linux-system-roles
        id: 35545
        imported: 2020-11-19T15:22:51.817393-05:00
        install_date: Fri Dec  4 13:29:11 2020
        **installed_version: 1.2.2**
        is_valid: True
        issue_tracker_url: https://github.com/linux-system-roles/storage/issues
        license: MIT
        min_ansible_version: 2.5
        modified: 2020-11-19T20:22:51.824145Z
`
