### ISSUE TITLE
defaults to xfs on RHEL 6 but xfsprogs does not seem to be available there

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/storage#20]
The role defaults to xfs on RHEL 6 but xfsprogs does not seem to be available there, so it fails by default.

**Comment by pcahyna** [comment]
I am pretty sure @timflannagan1 addressed it already in some commit/PR.

**Comment by timflannagan1** [comment]
@pcahyna correct, but the changes I made are fairly hacky. See e095664

**Comment by japokorn** [comment]
Since RHEL6 is not supported by the storage role and there are currently no plans of adding it, I am taking the liberty of closing this issue.
