### ISSUE TITLE
meta/requirements.yml is  not delivered with version1.6.2

### ISSUE THREAD

**Issue by crweller** [linux-system-roles/storage#233]
Hi, 
the installtion of this role via ansible-galaxy misses the mentioned requirements file.

Kind Regards,
Carl-Rainer Weller

**Comment by richm** [comment]
Would you know how I can add a dependency to a collection?  https://galaxy.ansible.com/linux-system-roles/storage now has a meta/requirements.yml https://github.com/linux-system-roles/storage/blob/master/meta/requirements.yml
but doing `ansible-galaxy role install linux-system-roles.storage` is either ignoring it, or the requirements file is in the wrong format?

**Comment by richm** [comment]
I've also tried to add a dependency on the collection to the meta/main.yml - dependencies - but I cannot figure out how to specify a collection

I would also suggest that if you are using ansible-core 2.11, you should use the https://galaxy.ansible.com/fedora/linux_system_roles collection instead - at some point we are going to deprecate support for the legacy role format, and new features will only be in the collection

**Comment by richm** [comment]
looks like the answer is no - https://github.com/ansible/ansible/issues/62847#issuecomment-756836439

**Comment by crweller** [comment]
Thank you for your reply.
I actually did install the roles/collections mentioned in the requirements file manually calling ansible-galaxy.

Sure a solution which takes care of the required roles/collections would be great.

I just asked to deliver the requirements file as part of the ansible-galaxy installation.

**Comment by richm** [comment]
> Thank you for your reply. I actually did install the roles/collections mentioned in the requirements file manually calling ansible-galaxy.
> 
> Sure a solution which takes care of the required roles/collections would be great.
> 
> I just asked to deliver the requirements file as part of the ansible-galaxy installation.

Ok, Thanks.  Then I'll close this issue as fixed by https://github.com/linux-system-roles/storage/pull/231
