### ISSUE TITLE
Fails on AlmaLinux 8

### ISSUE THREAD

**Issue by imgrant** [linux-system-roles/storage#239]
On AlmaLinux 8, this role fails at the first task, which loads a distribution-specific vars file:

```
TASK [fedora.linux_system_roles.storage : Set version specific variables] ************************************************************************************************************************
fatal: [almalinux8]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'first_found'. Error was a <class 'ansible.errors.AnsibleLookupError'>, original message: No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}
```

The reason is that there is no `AlmaLinux_8.yml` file with the role in `vars/` (nor `RedHat.yml` fallback). It looks like PR #211 fixes this & is good to merge (although maybe needs `vdo` and `kmod-vdo` packages adding?)

**Comment by AbdelAzizMohamedMousa** [comment]
It seems like the error message indicates that the lookup plugin 'first_found' was not able to find the required file. The issue could be resolved by adding an AlmaLinux_8.yml file with the required variables in the role's vars directory. As you mentioned, it looks like PR #211 addresses this issue by adding the missing file, so merging it should resolve the issue.

Regarding the VDO and kmod-vdo packages, if they are required for the role to work correctly on AlmaLinux 8, then it would be a good idea to add them as dependencies in the role's documentation or README file.
