### ISSUE TITLE
LVM thin provisioning support

### ISSUE THREAD

**Issue by vojtechtrefny** [linux-system-roles/storage#251]
We should add support for creating and managing LVM thin pools and thin LVs. Blivet already supports LVM thin provisioning so there shouldn't be anything extra need for storage role.

The question is whether it makes sense to add a new volume type, for example `lvmthin` or use the existing (default) `lvm` and just add a variable `thin: bool` for the volume.

**Comment by richm** [comment]
Any updates planned for this issue?

**Comment by vojtechtrefny** [comment]
@japokorn is currently working on this and if I understand it correctly he is finishing some few remaining corner cases in the thin provisioning support so we should have a PR ready for review soon. Can you provide some time estimate Jan?

**Comment by vojtechtrefny** [comment]
Closed via #269
