### ISSUE TITLE
Add support for creating and attaching cache volumes to existing volumes 

### ISSUE THREAD

**Issue by vojtechtrefny** [linux-system-roles/storage#252]
#235 is missing one important feature -- support for attaching cache to an existing volume which will now raise an exception, because blivet currently doesn't support creating the LVM cache pool separately, only creating the cache pool together with a new (cached) volume. This will change in the next blivet release (see https://github.com/storaged-project/blivet/pull/1004) and we plan to include this in the next RHEL release so we should add the support here too.

**Comment by richm** [comment]
Is there a PR for this issue?

**Comment by vojtechtrefny** [comment]
No, I haven't started working on the storage role part yet (the blivet support is already merged upstream and still planned for next RHEL release).
