### ISSUE TITLE
integration tests should clean up after themselves

### ISSUE THREAD

**Issue by dwlehman** [linux-system-roles/storage#27]
When running the integration tests anywhere other than in a throwaway vm it quickly becomes evident that some automated cleanup would be handy, both for the test runner's convenience and for the additional test coverage. The cleanup should probably only happen when the test validation was successful.

**Comment by pcahyna** [comment]
Yes, we did a similar thing for SELinux: https://github.com/linux-system-roles/selinux/pull/31. What exactly is needed to be cleaned up? Maybe @i386x or @vcrhonek could help?

**Comment by dwlehman** [comment]
At least when the tests succeed we clean up after ourselves as of #31, so I think we can close this.
