### ISSUE TITLE
RFE/Design question: Should the role support setting ownership/permissions of mount point

### ISSUE THREAD

**Issue by benblasco** [linux-system-roles/storage#274]
This role creates mount points during execution, but does not offer the option to define the ownership or permissions for those mount points.

Is this lack of functionality a deliberate design decision, a worthwhile RFE, or a bad idea?  I have discussed this with a colleague who thought it reasonable.

My example use case is the deployment of OpenShift Local (aka CodeReady Containers) as a regular user.  It requires a large volume of data to be available at ~<user>/.crc.  It would be reasonable to create this mount point with ownership and appropriate permissions for <user>.

Your feedback would be appreciated, and I may be able to contribute to the codebase if this is deemed worthwhile.

**Comment by Tronde** [comment]
Hello @benblasco,  
Though I'm not a contributer of this role I like your RFE pretty much.

IMHO it's not uncommon to run applications and services as a non-root user. Still these apps/services need to read/write data. When the role is capable of creating a mount point it seems perfectly reasonable to me that it's capabel of setting ownership and permissions as well.

**Comment by briansmith0** [comment]
This should be completed now with https://github.com/linux-system-roles/storage/pull/352   

@richm or @japokorn can you please close this issue?
