### ISSUE TITLE
Update README.md with Stratis information

### ISSUE THREAD

**Issue by briansmith0** [linux-system-roles/storage#455]
It appears that when using the role to configure Stratis you set the `type: stratis`, however the README.md file currently states that the only valid value for `type` is `lvm`.   Is there anything else Stratis specific that also needs to be included/updated in the README.md file?

**Comment by vojtechtrefny** [comment]
I think this should be the only place that needs to be updated. There are some news options for Stratis (for example `encryption_clevis_pin`) but I added those in the original Stratis PR. I found few more issues in the README and fixed them in #456
