### ISSUE TITLE
`eq` or `equalto` Jinja operators are not supported in Jinja 2.7.2 that is in RHEL7

### ISSUE THREAD

**Issue by pcahyna** [linux-system-roles/storage#49]
Even `eq` is not supported in Jinja 2.7.2 that is in RHEL7 . We need to use `==`. @yontalcar

_Originally posted by @pcahyna in https://github.com/linux-system-roles/storage/pull/26#issuecomment-543200427_

**Comment by yontalcar** [comment]
Problem here is that it is used as a test in `selectattr` filter:
https://github.com/linux-system-roles/storage/blob/master/tests/test-verify-volume-mount.yml#L4

**Comment by pcahyna** [comment]
@yontalcar then it needs to be rewritten - https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter perhaps?

**Comment by pcahyna** [comment]
Fixed in #56
