### ISSUE TITLE
fstype: swap not working 

### ISSUE THREAD

**Issue by parul1593** [linux-system-roles/storage#66]
Is swap supported as fs_type? Per documentation I see it is supported but when I run playbook, it says unknown fs_type.

I am using below playbook to create swap volume:
---
- hosts: localhost
  become: true
#  vars:
#    storage_use_partitions: true

  roles:
    - name: linux-system-roles.storage
      storage_pools:
        - name: app_data_01
          disks: ['/dev/sdb']
          #state: "absent"
          volumes:
            - name: data1
              fs_label: data1
              fs_type: ext4
              size: 10g
              mount_point: '/fs/data1'
        - name: data_02
          disks: ['/dev/sdc','/dev/sdd']
          #state: "absent"
          volumes:
            - name: data2
              size: 8g
              fs_type: swap
              mount_point: /fs/hdata2
            - name: data3
              mount_options: 'ro,noatime'
              fs_type: xfs
              size: 2g
              mount_point: /fs/data3

This is the error which I get
"msg": "Error mounting /fs/hdata2: mount: unknown filesystem type 'swap'\n"

**Comment by dwlehman** [comment]
Swap cannot have a mount point. It does not actually get mounted; it gets activated instead.

**Comment by parul1593** [comment]
If I dont give a mountpoint, then it goes through fine. But there is no entry in /etc/fstab and I dont see any swap getting added. I ran "swapon -a" also.

Using this playbook:
`---
- hosts: localhost
  become: true
#  vars:
#    storage_use_partitions: true

  roles:
    - name: linux-system-roles.storage
      storage_pools:
        - name: app_data_01
          disks: ['/dev/sdb']
          #state: "absent"
          volumes:
            - name: data1
              fs_label: data1
              fs_type: ext4
              size: 10g
              mount_point: '/fs/data1'
        - name: app_data_02
          disks: ['/dev/sdc','/dev/sdd']
          #state: "absent"
          volumes:
            - name: data2
              size: 4g
              fs_type: ext4
              mount_point: /fs/data2
              #mount_options: 'noatime'
              #type: lvm
              #fs_overwrite_existing: false
            - name: data3
              #mount_options: 'ro,noatime'
              fs_type: swap
              size: 15g
`

output of lsblk:
NAME                 MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0                    2:0    1    4K  0 disk
sda                    8:0    0   64G  0 disk
|-sda1                 8:1    0  512M  0 part /boot/efi
|-sda2                 8:2    0  512M  0 part /boot
|-sda3                 8:3    0    2M  0 part
`-sda4                 8:4    0   63G  0 part
  |-vg0-lvroot       253:0    0   16G  0 lvm  /
  |-vg0-lvswap       253:1    0    4G  0 lvm  [SWAP]
  |-vg0-lvvarlog     253:5    0    4G  0 lvm  /var/log
  |-vg0-lvafscache   253:6    0   12G  0 lvm  /local/afs.cache
  |-vg0-lvlocal      253:7    0   19G  0 lvm  /local
  |-vg0-lvvartmp     253:8    0    4G  0 lvm  /var/tmp
  `-vg0-lvtmp        253:9    0    4G  0 lvm  /tmp
sdb                    8:16   0   60G  0 disk
`-app_data_01-data1 253:4    0   10G  0 lvm  /fs/data1
sdc                    8:32   0  100G  0 disk
|-app_data_02-data3 253:2    0   15G  0 lvm
`-app_data_02-data2 253:3    0    4G  0 lvm  /fs/data2

**Comment by dwlehman** [comment]
> If I dont give a mountpoint, then it goes through fine. But it does not enable it and there is no entry in /etc/fstab. Is this the expected behaviour?

No, that is a bug. It should appear in /etc/fstab based on your playbook.

**Comment by dwlehman** [comment]
I am working on a fix now for the swap issue you found. There is already a proposed change to improve the error message when a mount point is given for a swap volume. Now I am working on the problem of swaps not being correctly managed in /etc/fstab, including regression test coverage.

BTW, you have to use triple backticks to start/end multi-line code blocks.

**Comment by dwlehman** [comment]
I have what seems to be a working solution for swap in #68.

**Comment by parul1593** [comment]
Thanks for getting us the fix. Which version of storage-roles will have the fix available?
