### ISSUE TITLE
Create storage_lsr sub-directory under module_utils and move size.py there

### ISSUE THREAD

**Issue by t-woerner** [linux-system-roles/storage#67]
The module_utils script size.py is not following the naming scheme for linux-system-roles. Please add a proper prefix to the name.

**Comment by richm** [comment]
The storage role `module_utils` should have a sub-directory called `storage_lsr/` which contains `size.py`

**Comment by richm** [comment]
Using a unique sub-directory under module_utils will also help conversion to collection
