### ISSUE TITLE
storage: fatal: [localhost]: FAILED! => {"reason": "couldn't resolve module/action 'mount'.

### ISSUE THREAD

**Issue by yizhanglinux** [linux-system-roles/storage#77]
Observed this error when I use the latest ansible, but cannot reproduce it with ansible 2.9.6, pls help check it.

[root@storageqe-62 storage]# ansible-playbook  -i inventory tests/tests_default.yml
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.

PLAY [Ensure that the role runs with default parameters] ******************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [storage : Set version specific variables] ***************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=/root/storage/vars/RedHat-8.yml)

TASK [storage : define an empty list of pools to be used in testing] ******************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [storage : define an empty list of volumes to be used in testing] ****************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [storage : include the appropriate provider tasks] *******************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"reason": "couldn't resolve module/action 'mount'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/root/storage/tasks/main-blivet.yml': line 132, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#\n- name: manage mounts to match the specified state\n  ^ here\n"}

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

[root@storageqe-62 storage]# ansible --version
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
ansible 2.10.0.dev0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible_base-2.10.0.dev0-py3.6.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121]

**Comment by dwlehman** [comment]
There was a big recent change in upstream ansible which moved most of the previously-standard modules out to a separate repository.

Further info:

https://groups.google.com/forum/#!msg/ansible-devel/oKqgCeYTs-M/cHrOgMw8CAAJ
https://github.com/ansible-collections/overview/blob/master/README.rst

**Comment by pcahyna** [comment]
`mount` should be in the `posix` collection.

**Comment by yizhanglinux** [comment]
Thanks, do we have plan to fix it on storage role?

**Comment by pcahyna** [comment]
We will handle those issues consistently in all system roles. But, AFAIK, there will be an Ansible distribution that will behave exactly as now, so nothing will need to be fixed. I don't know whether it is already available.
For now, can you please try importing the `posix` collection in your playbook before calling the storage role?

**Comment by yizhanglinux** [comment]
> We will handle those issues consistently in all system roles. But, AFAIK, there will be an Ansible distribution that will behave exactly as now, so nothing will need to be fixed. I don't know whether it is already available.
> For now, can you please try importing the `posix` collection in your playbook before calling the storage role?

Sure, but currently I'm not familiar with it, could you tell me how to import it? we can take the bellow case as an example, thanks.
https://github.com/linux-system-roles/storage/blob/master/tests/tests_default.yml

**Comment by yizhanglinux** [comment]
> > We will handle those issues consistently in all system roles. But, AFAIK, there will be an Ansible distribution that will behave exactly as now, so nothing will need to be fixed. I don't know whether it is already available.
> > For now, can you please try importing the `posix` collection in your playbook before calling the storage role?
> 
> Sure, but currently I'm not familiar with it, could you tell me how to import it? we can take the bellow case as an example, thanks.
> https://github.com/linux-system-roles/storage/blob/master/tests/tests_default.yml

When I use posix collection in my playbook, found one issue for the mount module, I've filed bellow issue to track it.

https://github.com/ansible-collections/ansible.posix/issues/21

**Comment by pcahyna** [comment]
Thank you for investigating this issue and reporting it, and sorry for not providing advice on transitioning to collections, I have not really started this transition myself.

**Comment by yizhanglinux** [comment]
The ansible.posix issue was fixed now.

**Comment by japokorn** [comment]
I am closing this issue because it is already resolved.
