### ISSUE TITLE
[RFE] lvm raid

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/storage#79]
Hi,
I'm looking to use striped volumes for SAP HANA on Azure. Blivet itself seems to have these capabilities. It would be a good idea to incorporate it into this role.

SAP HANA on Azure needs striped raid0 with different blocksizes (https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-storage)

Greetings
Klaas

**Comment by pcahyna** [comment]
@dwlehman @japokorn Hello, is it something that you want to support?

**Comment by pcahyna** [comment]
@berndfinger is it something that the SAP team would make use of? Is this an usual/recommended configuration?

**Comment by dwlehman** [comment]
Development is well under way now for MD RAID support (for volumes or entire LVM pools). LVM RAID support is on our radar, but not currently scheduled.

Am I correct in assuming/guessing that what the Azure docs refer to as "stripe size" is what mdadm calls "chunk size"?

**Comment by dwlehman** [comment]
This functionality was added in #241.
