### ISSUE TITLE
No libblockdev-dm in RHEL 7.6

### ISSUE THREAD

**Issue by rickgcv** [linux-system-roles/storage#89]
The playbook fails in RHEL 7.6 because libblockdev-lvm is not available for this OS version

**Comment by dwlehman** [comment]
libblockdev-lvm is definitely available in RHEL-7.6. I checked Server, Client, and Workstation.

**Comment by rickgcv** [comment]
Sorry, it is ibblockdev-dm the one I can't seem to find for RHEL 7.6 (modified the name of the issue)

**Comment by rickgcv** [comment]
Many thanks, it was indeed in the optional repos.
